# Generated by Django 2.0.4 on 2018-05-02 12:41

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classId', models.CharField(max_length=20, verbose_name='班级编号')),
                ('className', models.CharField(max_length=20, verbose_name='班级名称')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=20, verbose_name='姓名')),
                ('studentpassword', models.CharField(max_length=20, verbose_name='密码')),
                ('studentClass', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='app1.Classes', verbose_name='班级')),
            ],
        ),
    ]
