# Generated by Django 2.0.4 on 2018-05-05 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherName', models.CharField(max_length=20, verbose_name='姓名')),
                ('teacherPassword', models.CharField(max_length=20, verbose_name='姓名')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
                'db_table': 'teacherUser',
            },
        ),
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name': '班级', 'verbose_name_plural': '班级'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
        migrations.AlterField(
            model_name='student',
            name='studentClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Classes', verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(to='app1.Classes'),
        ),
    ]
