# Generated by Django 2.0.4 on 2018-05-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20180505_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagesUrl', models.CharField(max_length=200, verbose_name='图片路径')),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(related_name='xxx', to='app1.Classes'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacherPassword',
            field=models.CharField(max_length=20, verbose_name='密码'),
        ),
    ]
